### ISSUE TITLE
Yelp - Review my app

### ISSUE THREAD

**Issue by kevinho6** [bornarkun/week3#2]
My app is complete, please review. /cc @codepathreview

**Comment by minhchau273** [comment]
:+1: Nice work! This primary challenge of this homework was to learn how to use AutoLayout to build adaptive UI's that work across many different screen sizes and orientations. If you haven't already, we recommend going back and running your homework again while rotating the device / simulator to ensure your AutoLayout constraints function as expected.

### Some small comments:
- Note that you should resolve all the Auto Layout constraint warnings in your nibs.
- It's a little bit hard to tap the search bar.
  <img width="320" alt="screen shot 2016-02-16 at 5 32 19 pm" src="https://cloud.githubusercontent.com/assets/12395213/13073807/555fea4e-d4d3-11e5-82f2-a37268bc3b64.png">
- For now, you only search within the current restaurants. In this assignment, you have to call the api to search the restaurants.

We have a detailed [Project 3 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_3_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
